"use client";

import { motion } from "framer-motion";

interface ApplicationSection {
  readonly title: string;
  readonly intro: string;
  readonly items: readonly string[];
  readonly benefits: string;
}

const APPLICATION_SECTIONS: readonly ApplicationSection[] = [
  {
    title: "Consumer Electronics",
    intro:
      "Thermal grease, phase change materials (PCM), and FlexiMetal (35W/mK) manage heat in compact, high-performance devices. Applied between CPU/GPU and active cooling paths, it ensures efficient heat transfer where space is at a premium.",
    items: [
      "Laptops - high-performance processors in thin form factors",
      "Smartphones - 5G processors generating significant heat",
      "Gaming consoles - Xbox, PlayStation PS5 with sustained workloads",
    ],
    benefits:
      "Prevents thermal throttling, extends device lifespan, and enables quieter operation by reducing fan speeds.",
  },
  {
    title: "Automotive & Electric Vehicles",
    intro:
      "Manages heat from batteries and power electronics in EVs. Thermal interface materials help dissipate heat during charging and discharging cycles, protecting critical components.",
    items: [
      "Battery cells - thermal regulation during fast charging",
      "Inverters, converters, and motor controllers",
      "Engine control units and onboard electronics",
    ],
    benefits:
      "Extends battery lifespan, improves overall efficiency, and ensures safe operation under demanding thermal conditions.",
  },
  {
    title: "Data Centers & Servers",
    intro:
      "Critical for managing the intense heat generated by CPUs and GPUs in server environments. Thermal interface materials reduce thermal resistance and prevent throttling or hardware damage.",
    items: [
      "Cloud computing infrastructure",
      "High-performance computing clusters",
      "Dense server stacks and blade servers",
    ],
    benefits:
      "Lowers energy consumption for cooling, reduces operating costs, and prevents costly downtime from thermal failures.",
  },
  {
    title: "Aerospace, Medical & Industrial",
    intro:
      "Used in extreme conditions where thermal performance directly impacts safety and reliability. These applications demand materials that perform across wide temperature ranges.",
    items: [
      "Aerospace - avionics systems, satellite electronics",
      "Medical - MRI machines, ultrasound imaging devices",
      "Industrial - robotic arms, CNC machines, power modules",
    ],
    benefits:
      "Maintains optimal operating temperatures, extends operational life, and ensures compliance with rigorous safety standards.",
  },
  {
    title: "Sustainability & Environmental Impact",
    intro:
      "Enhanced thermal efficiency reduces energy consumption and lowers carbon footprint across all applications. The industry is advancing eco-friendly, non-toxic, and recyclable thermal materials.",
    items: [
      "Extended EV battery lifespan through better thermal management",
      "Reduced data center energy consumption via improved cooling",
      "Development of non-toxic, recyclable thermal interface materials",
    ],
    benefits:
      "Lower environmental impact, reduced total cost of ownership, and alignment with global sustainability goals.",
  },
];

const sectionVariants = {
  hidden: { opacity: 0, y: 50 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.6, ease: "easeOut" as const },
  },
};

export default function ApplicationsPage() {
  return (
    <section className="min-h-screen bg-dm-midnight pt-24 pb-6 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl">
        {/* Header */}
        <motion.div
          className="text-center mb-6"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-4xl sm:text-5xl font-bold text-gradient mb-4">
            Applications
          </h1>
          <p className="text-lg text-dm-gray max-w-2xl mx-auto">
            Thermal interface materials powering innovation across industries
          </p>
        </motion.div>

        {/* Sections */}
        <div className="space-y-6">
          {APPLICATION_SECTIONS.map((section, idx) => {
            const isReversed = idx % 2 !== 0;

            return (
              <motion.div
                key={section.title}
                className={`flex flex-col ${
                  isReversed ? "lg:flex-row-reverse" : "lg:flex-row"
                } gap-8 items-stretch`}
                variants={sectionVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true, margin: "-80px" }}
              >
                {/* Title panel */}
                <div className="lg:w-2/5 flex items-center">
                  <div className="w-full rounded-2xl glass glow-border p-8 flex flex-col justify-center">
                    <h2 className="text-2xl sm:text-3xl font-bold text-dm-white">
                      {section.title}
                    </h2>
                  </div>
                </div>

                {/* Content panel */}
                <div className="lg:w-3/5 rounded-2xl glass p-8 border border-dm-slate/30">
                  <p className="text-dm-gray-light leading-relaxed mb-5">
                    {section.intro}
                  </p>

                  <ul className="space-y-3 mb-5">
                    {section.items.map((item) => (
                      <li key={item} className="flex items-start gap-3">
                        <span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-dm-accent" />
                        <span className="text-sm text-dm-gray leading-relaxed">
                          {item}
                        </span>
                      </li>
                    ))}
                  </ul>

                  <div className="rounded-lg bg-dm-accent/5 border border-dm-accent/10 px-4 py-3">
                    <p className="text-sm text-dm-accent-light leading-relaxed">
                      {section.benefits}
                    </p>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
